services:
  app:
    image: ghcr.io/pel-matiasvaldivia/lgm-cotizador:master
    container_name: logmetal_app
    restart: unless-stopped
    ports:
      - "3300:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
